### ISSUE TITLE
support for null safety

### ISSUE THREAD

**Issue by davidAg9** [frencojobs/envify#11]

**Comment by davidAg9** [comment]
envify analyser dependency must be upgraded

**Comment by frencojobs** [comment]
I've updated the `envify` packaged to null-safety for a while. The reason why I haven't worked on the `envify_generator` is because it's being blocked by https://github.com/dart-lang/source_gen/issues/493.

**Comment by JEuler** [comment]
@frencojobs Source gen is now upgraded for null safety (#13). Do you need any help to upgrade the generator?

**Comment by frencojobs** [comment]
Hey, Frenco here.

Due to current situations regarding my country with consistent internet blackouts and GitHub being banned, I won't be able to focus on things for now. I hope you could understand.

If I'm not mistaken, the code itself needs some modifications to migrate to null safety. I won't be able to do that right at the moment. But if you need null safe envify to use in a project or something important, feel free to submit a PR :pray:. I could probably give time to check PRs and publish the package. Thanks. (Also sorry if PRs are reviewed late, I'll try to review and merge them as fast as I could.)

**Comment by JEuler** [comment]
Oh, okay! Stay safe! I Will try to migrate the generator code for null safety, thank you!

**Comment by JEuler** [comment]
I have upgraded the PR for null safety conversion (just run the `dart migrate` and checked tests - seems working). Will recheck the output of conversion later. 

Anyway, take your time and stay safe!

**Comment by frencojobs** [comment]
The generator v2.0.0 is now null-safe making envify a null-safe library now :tada:. Thank you very much @JEuler for the contribution.
