### ISSUE TITLE
How to automatically get the “current settings”?

### ISSUE THREAD

**Issue by ksilz** [frencojobs/envify#4]
Hi!

I want to have parameters in my Flutter app that are different between debug and production. In my Spring Boot Java application, I get this automatically: I got two set of config files and pass in “debug/production” as a profile name into my application. Then Spring Boot automatically picks the right config file.

How do I achieve this with your package in Flutter? You gave this example: 

```dart
@Envify(path: '.env.development')
abstract class DevEnv {}

@Envify(path: '.env.production')
abstract class ProdEnv {}
```

So I assume that I need to configure these two different “parameter classes”. Then my code needs to manually pick the right one, based on whether I’m in debug or production. Correct?

Regards,
Karsten Silz

**Comment by frencojobs** [comment]
I can't make envify to pick the right file based on whether it is production or not because there's no such thing as modes in Dart. But in Flutter, you can use [`kReleaseMode`](https://api.flutter.dev/flutter/foundation/kReleaseMode-constant.html) from `foundation.dart` to conditionally determine the path. Here's a complete example,

```dart
import 'package:flutter/foundation.dart';

@Envify(path: kReleaseMode ? '.env.production' : '.env.development')
abstract class Env {}
```

Hope you have a good day!

**Comment by ksilz** [comment]
Thank you!

**Comment by anamauad** [comment]
What is the command that someone needs to use in order to compile to **release mode**?

When I use
```
flutter packages pub run build_runner build
```
the `env.g.dart` file is being created using the keys from the `.env.development` file.

**Comment by Paradoxu** [comment]
> What is the command that someone needs to use in order to compile to **release mode**?
> 
> When I use
> 
> ```
> flutter packages pub run build_runner build
> ```
> 
> the `env.g.dart` file is being created using the keys from the `.env.development` file.

Have you found a solution? I'm still trying to figure how to tell `envify` to use `.env.production` on release...

**Comment by frencojobs** [comment]
Omg, why didn't I see this. Sorry about the delay in response. Seems like that `kReleaseMode` trick doesn't actually work because `build_runner` is only run during development. I'm terribly sorry for this. I'll find a workaround to solve this issue. In the meantime, I'll remove that not-working-trick from the documentation.
